---

version: "v-{build}"

image: Visual Studio 2022

clone_folder: C:\projects\dictim

environment:
  GRAALVM_HOME: C:\projects\dictim\graalvm\graalvm-community-openjdk-21.0.2+13.1
  BABASHKA_XMX: "-J-Xmx5g"
  GITHUB_TOKEN:
    secure: wc1t+ZLDldNPTC6DlMrh4GeD83f4VlSX36Pj5tQsCDHuJsco9Vmg3P9Xg61o5Ow5HWGq5I92Yt2HeojHgI/t7drWyaND1SMR6YgrCBV2sS9sjAEeWCuPl+0t61bBzxZ0

cache:
  - '%USERPROFILE%\.m2 -> deps.edn'
  - '%USERPROFILE%\.gitlibs -> deps.edn'
  - 'graalvm -> appveyor.yml'

build_script:

- cmd: >-
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_windows-x64_bin.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/borkdude/babashka/releases/download/v1.3.190/babashka-1.3.190-windows-amd64.zip', 'bb.zip') }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { Expand-Archive bb.zip . }"

    powershell -Command "if (Test-Path('clojure.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/casselc/clj-msi/releases/download/v1.11.3.1463/clojure-1.11.3.1463.msi', 'clojure.msi') }"

    powershell -Command "msiexec.exe /i clojure.msi /qn"

- cmd: >-
    call script/compile.bat

    set /P VERSION=< resources\VERSION

    set ARCHIVE=dictim-%VERSION%-windows-amd64.zip


deploy:
  tag: v$(APPVEYOR_BUILD_VERSION)
  description: 'dictim release %VERSION%'
  provider: GitHub
  auth_token:
    secure: wc1t+ZLDldNPTC6DlMrh4GeD83f4VlSX36Pj5tQsCDHuJsco9Vmg3P9Xg61o5Ow5HWGq5I92Yt2HeojHgI/t7drWyaND1SMR6YgrCBV2sS9sjAEeWCuPl+0t61bBzxZ0
  artifact: %ARCHIVE%
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: main
    APPVEYOR_REPO_TAG: false