---

version: "v-{build}"

image: Visual Studio 2017

clone_folder: C:\projects\dictim

environment:
  GRAALVM_HOME: C:\projects\babashka\graalvm\graalvm-ce-java17-22.3.0
  BABASHKA_XMX: "-J-Xmx5g"

cache:
  - '%USERPROFILE%\.m2 -> deps.edn'
  - '%USERPROFILE%\.gitlibs -> deps.edn'
  - 'graalvm -> appveyor.yml'

build_script:

- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-windows-amd64-22.3.0.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/borkdude/babashka/releases/download/v1.0.169/babashka-1.3.190-windows-amd64.zip', 'bb.zip') }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { Expand-Archive bb.zip . }"

    powershell -Command "if (Test-Path('clojure.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/casselc/clj-msi/releases/download/v1.11.3.1463/clojure-1.11.3.1463.msi', 'clojure.msi') }"

    powershell -Command "msiexec.exe /i clojure.msi /qn"

- cmd: >-
    call script/compile.bat

    set /P VERSION=< resources\VERSION

    set ARCHIVE=dictim-%VERSION%-windows-amd64.zip
