version: 2.1

jobs:
  test:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0

    working_directory: ~/project
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.11.1.1149.sh
            chmod +x linux-install-1.11.1.1149.sh
            sudo ./linux-install-1.11.1.1149.sh
      - run:
          name: run clj tests
          command: |
            clojure -X:test
      - run:
          name: install babashka
          command: |
            sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
      - run:
          name: run bb tests
          command: |
            bb test:bb
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}
      - run:
          name: echo TOKEN
          command: printenv GITHUB_TOKEN
  release:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0

    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
      - run:
          name: install babashka
          command: |
            sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
      - run:
          name: build bb uberjar
          command: |
            bb build
      - run:
          name: release artifact
          command: |
            .circleci/script/release
      - run:
          name: install bbin
          command: |
            mkdir -p ~/.local/bin && curl -o- -L https://raw.githubusercontent.com/babashka/bbin/v0.2.1/bbin > ~/.local/bin/bbin && chmod +x ~/.local/bin/bbin
            echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.$(basename $SHELL)rc && exec $SHELL
      - run:
          name: install dictim via bbin
          command: |
            bbin install https://github.com/judepayne/dictim/releases/latest/download/dictim.jar
      - run:
          name: run dictim command tests
          command: |
            bb test/cmd_test.clj

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "bb.edn" }}
      

workflows:
  test-and-release-on-main:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: main
