version: 2.1

jobs:
  test:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0

    working_directory: ~/project
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.11.1.1149.sh
            chmod +x linux-install-1.11.1.1149.sh
            sudo ./linux-install-1.11.1.1149.sh
      - run:
          name: run tests
          command: |
            clojure -X:test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      

workflows:
  test-workflow:
    jobs:
      - test